//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NATILLERAEntities : DbContext
    {
        public NATILLERAEntities()
            : base("name=NATILLERAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAhorro> tblAhorros { get; set; }
        public virtual DbSet<tblAlquilere> tblAlquileres { get; set; }
        public virtual DbSet<tblAuditoria> tblAuditorias { get; set; }
        public virtual DbSet<tblCliente> tblClientes { get; set; }
        public virtual DbSet<tblEvento> tblEventos { get; set; }
        public virtual DbSet<tblLiquidacione> tblLiquidaciones { get; set; }
        public virtual DbSet<tblPagosPrestamo> tblPagosPrestamoes { get; set; }
        public virtual DbSet<tblParticipantesEvento> tblParticipantesEventos { get; set; }
        public virtual DbSet<tblPrestamo> tblPrestamos { get; set; }
        public virtual DbSet<tblProveedore> tblProveedores { get; set; }
        public virtual DbSet<tblSede> tblSedes { get; set; }
        public virtual DbSet<tblTiposTransaccion> tblTiposTransaccions { get; set; }
        public virtual DbSet<tblToken> tblTokens { get; set; }
        public virtual DbSet<tblTransaccione> tblTransacciones { get; set; }
        public virtual DbSet<tblUsuario> tblUsuarios { get; set; }
    }
}
