//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlquilere
    {
        public int intIdAlquilerPk { get; set; }
        public int intIdSedeFk { get; set; }
        public int intIdProveedorFk { get; set; }
        public string varLugar { get; set; }
        public decimal decCosto { get; set; }
        public System.DateTime dtFechaAlquiler { get; set; }
    
        public virtual tblSede tblSede { get; set; }
        public virtual tblProveedore tblProveedore { get; set; }
    }
}
