//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlquilere
    {
        public int intIdAlquilerPk { get; set; }
        public int intIdSedeFk { get; set; }
        public int intIdProveedorFk { get; set; }
        public string varLugar { get; set; }
        public decimal decCosto { get; set; }
        public System.DateTime dtFechaAlquiler { get; set; }

        [JsonIgnore]
        public virtual tblSede tblSede { get; set; }
        [JsonIgnore]

        public virtual tblProveedore tblProveedore { get; set; }
    }
}
