//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAhorro
    {
        public int intIdAhorroPk { get; set; }
        public int intIdClienteFk { get; set; }
        public int intIdSedeFk { get; set; }
        public decimal decMonto { get; set; }
        public System.DateTime dtFechaAhorro { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblSede tblSede { get; set; }
    }
}
