//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditoria
    {
        public int intIdAuditoriaPk { get; set; }
        public int intIdUsuarioFk { get; set; }
        public int intIdSedeFk { get; set; }
        public string varAccion { get; set; }
        public string txtDescripcion { get; set; }
        public Nullable<System.DateTime> dtFechaRegistro { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblSede tblSede { get; set; }
    }
}
