//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditoria
    {
        public int intIdAuditoriaPk { get; set; }
        public int intIdUsuarioFk { get; set; }
        public int intIdSedeFk { get; set; }
        public string varAccion { get; set; }
        public string txtDescripcion { get; set; }
        public Nullable<System.DateTime> dtFechaRegistro { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblSede tblSede { get; set; }
    }
}
