//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvento()
        {
            this.tblParticipantesEventos = new HashSet<tblParticipantesEvento>();
        }
    
        public int intIdEventoPk { get; set; }
        public int intIdSedeFk { get; set; }
        public string varNombreEvento { get; set; }
        public string enmTipo { get; set; }
        public System.DateTime dtFechaInicio { get; set; }
        public Nullable<System.DateTime> dtFechaFin { get; set; }

        [JsonIgnore]
        public virtual tblSede tblSede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblParticipantesEvento> tblParticipantesEventos { get; set; }
    }
}
