//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvento()
        {
            this.tblParticipantesEventos = new HashSet<tblParticipantesEvento>();
        }
    
        public int intIdEventoPk { get; set; }
        public int intIdSedeFk { get; set; }
        public string varNombreEvento { get; set; }
        public string enmTipo { get; set; }
        public System.DateTime dtFechaInicio { get; set; }
        public Nullable<System.DateTime> dtFechaFin { get; set; }
    
        public virtual tblSede tblSede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblParticipantesEvento> tblParticipantesEventos { get; set; }
    }
}
