//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLiquidacione
    {
        public int intIdLiquidacionPk { get; set; }
        public int intIdClienteFk { get; set; }
        public int intIdSedeFk { get; set; }
        public decimal decMontoTotal { get; set; }
        public System.DateTime dtFechaLiquidacion { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblSede tblSede { get; set; }
    }
}
