//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPagosPrestamo
    {
        public int intIdPagoPk { get; set; }
        public int intIdPrestamoFk { get; set; }
        public int intIdSedeFk { get; set; }
        public decimal decMontoCapital { get; set; }
        public decimal decMontoInteres { get; set; }
        public Nullable<System.DateTime> dtFechaPago { get; set; }
    
        public virtual tblPrestamo tblPrestamo { get; set; }
        public virtual tblSede tblSede { get; set; }
    }
}
