//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPagosPrestamo
    {
        public int intIdPagoPk { get; set; }
        public int intIdPrestamoFk { get; set; }
        public int intIdSedeFk { get; set; }
        public decimal decMontoCapital { get; set; }
        public decimal decMontoInteres { get; set; }
        public Nullable<System.DateTime> dtFechaPago { get; set; }
    
        public virtual tblPrestamo tblPrestamo { get; set; }
        public virtual tblSede tblSede { get; set; }
    }
}
