//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParticipantesEvento
    {
        public int intIdParticipacionPk { get; set; }
        public int intIdEventoFk { get; set; }
        public int intIdUsuarioFk { get; set; }
        public string enmRol { get; set; }
    
        public virtual tblEvento tblEvento { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
