//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaccione
    {
        public int intIdTransaccionPk { get; set; }
        public int intIdClienteFk { get; set; }
        public int intIdTipoTransaccionFk { get; set; }
        public int intIdUsuarioRegistroFk { get; set; }
        public int intIdSedeFk { get; set; }
        public decimal decMonto { get; set; }
        public Nullable<System.DateTime> dtFechaOperacion { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblSede tblSede { get; set; }
        public virtual tblTiposTransaccion tblTiposTransaccion { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
