//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblToken
    {
        public int intIdTokenPk { get; set; }
        public int intIdUsuarioFk { get; set; }
        public string varToken { get; set; }
        public System.DateTime dtExpiracion { get; set; }
        public string enmTipo { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
