//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblToken
    {
        public int intIdTokenPk { get; set; }
        public int intIdUsuarioFk { get; set; }
        public string varToken { get; set; }
        public System.DateTime dtExpiracion { get; set; }
        public string enmTipo { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
