//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATILLERA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaccione
    {
        public int intIdTransaccionPk { get; set; }
        public int intIdClienteFk { get; set; }
        public int intIdTipoTransaccionFk { get; set; }
        public int intIdUsuarioRegistroFk { get; set; }
        public int intIdSedeFk { get; set; }
        public decimal decMonto { get; set; }
        public Nullable<System.DateTime> dtFechaOperacion { get; set; }
       
        [JsonIgnore]
        public virtual tblCliente tblCliente { get; set; }
        [JsonIgnore]
        public virtual tblSede tblSede { get; set; }
        [JsonIgnore]
        public virtual tblTiposTransaccion tblTiposTransaccion { get; set; }
        [JsonIgnore]
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
